import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import AddTask from "@/components/AddTask";
import TodoList from "@/components/TodoList";
import React, { useEffect, useState } from "react";
import { ITask } from "../../types/tasks";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState<ITask[]>([]);
  useEffect(() => {
    async function getAllTasks(): Promise<ITask> {
      const response = await fetch("http://localhost:3001/tasks", {
        cache: "no-store",
      });
      const tasks = await response.json();
      setData(tasks);
      return tasks;
    }
    getAllTasks();
  }, []);
  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.section}>
          <h1>Todo App</h1>
          <AddTask></AddTask>
          <TodoList tasks={data}></TodoList>
        </div>
      </main>
    </>
  );
}
